### ISSUE TITLE
Support for multiple zabbix servers

### ISSUE THREAD

**Issue by ghost** [shamil/puppet-zabbix-reports#3]
This is a very neat module. I would like to have the ability to report to multiple zabbix servers in parallell. In our system we have several zabbix servers for different parts of the system and sometimes an additional zabbix for development and testing new versions etc. but a single puppet server for it all. So multiple zabbix servers would be useful.

**Comment by shamil** [comment]
Implemented. With help of #5. 
Thanks to @erikoest
